version: "3"

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgressql/data
    networks:
      - strapi-network

  strapi:
    image: strapi/strapi:latest
    container_name: strapi-container
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${POSTGRES_DB}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - postgres
    ports:
      - '1337:1337'
    volumes:
      - ./strapi_app:/srv/app
    networks:
      - strapi-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - strapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - strapi-network

volumes:
  postgres_data:

networks:
  strapi-network:
    name: strapi-network





    
